// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmustache.proxies;

public enum PrimitiveType
{
	String(new String[][] { new String[] { "en_US", "String" } }),
	_Boolean(new String[][] { new String[] { "en_US", "Boolean" } }),
	Number(new String[][] { new String[] { "en_US", "Number" } }),
	_NULL(new String[][] { new String[] { "en_US", "NULL" } });

	private java.util.Map<String,String> captions;

	private PrimitiveType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
