// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxlists.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mxlists.proxies.SeriesItem;
import java.util.ArrayList;

public class GenerateLongSeries extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.Long StartValue;
	private java.lang.Long EndValue;
	private java.lang.Long Interval;

	public GenerateLongSeries(IContext context, java.lang.Long StartValue, java.lang.Long EndValue, java.lang.Long Interval)
	{
		super(context);
		this.StartValue = StartValue;
		this.EndValue = EndValue;
		this.Interval = Interval;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		ArrayList<IMendixObject> resultList = new ArrayList<IMendixObject>();
		for(Long i = StartValue; i <= EndValue ;  i = i + Interval){
			SeriesItem item = new SeriesItem(getContext());
			item.setLongValue(i);
			resultList.add(item.getMendixObject());
		}
		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GenerateLongSeries";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
