// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmustachetests.proxies;

public class Car
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject carMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxMustacheTests.Car";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CarId("CarId"),
		Brand("Brand"),
		Model("Model"),
		Doors("Doors"),
		Price("Price"),
		HasTurbo("HasTurbo"),
		DateIntroduction("DateIntroduction"),
		Color("Color"),
		Car_CarList("MxMustacheTests.Car_CarList");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Car(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxMustacheTests.Car"));
	}

	protected Car(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject carMendixObject)
	{
		if (carMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxMustacheTests.Car", carMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxMustacheTests.Car");

		this.carMendixObject = carMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Car.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxmustachetests.proxies.Car initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxmustachetests.proxies.Car.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mxmustachetests.proxies.Car initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxmustachetests.proxies.Car(context, mendixObject);
	}

	public static mxmustachetests.proxies.Car load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxmustachetests.proxies.Car.initialize(context, mendixObject);
	}

	public static java.util.List<mxmustachetests.proxies.Car> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mxmustachetests.proxies.Car> result = new java.util.ArrayList<mxmustachetests.proxies.Car>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MxMustacheTests.Car" + xpathConstraint))
			result.add(mxmustachetests.proxies.Car.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CarId
	 */
	public final java.lang.Long getCarId()
	{
		return getCarId(getContext());
	}

	/**
	 * @param context
	 * @return value of CarId
	 */
	public final java.lang.Long getCarId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CarId.toString());
	}

	/**
	 * Set value of CarId
	 * @param carid
	 */
	public final void setCarId(java.lang.Long carid)
	{
		setCarId(getContext(), carid);
	}

	/**
	 * Set value of CarId
	 * @param context
	 * @param carid
	 */
	public final void setCarId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long carid)
	{
		getMendixObject().setValue(context, MemberNames.CarId.toString(), carid);
	}

	/**
	 * @return value of Brand
	 */
	public final java.lang.String getBrand()
	{
		return getBrand(getContext());
	}

	/**
	 * @param context
	 * @return value of Brand
	 */
	public final java.lang.String getBrand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Brand.toString());
	}

	/**
	 * Set value of Brand
	 * @param brand
	 */
	public final void setBrand(java.lang.String brand)
	{
		setBrand(getContext(), brand);
	}

	/**
	 * Set value of Brand
	 * @param context
	 * @param brand
	 */
	public final void setBrand(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brand)
	{
		getMendixObject().setValue(context, MemberNames.Brand.toString(), brand);
	}

	/**
	 * @return value of Model
	 */
	public final java.lang.String getModel()
	{
		return getModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Model
	 */
	public final java.lang.String getModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Model.toString());
	}

	/**
	 * Set value of Model
	 * @param model
	 */
	public final void setModel(java.lang.String model)
	{
		setModel(getContext(), model);
	}

	/**
	 * Set value of Model
	 * @param context
	 * @param model
	 */
	public final void setModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String model)
	{
		getMendixObject().setValue(context, MemberNames.Model.toString(), model);
	}

	/**
	 * @return value of Doors
	 */
	public final java.lang.Integer getDoors()
	{
		return getDoors(getContext());
	}

	/**
	 * @param context
	 * @return value of Doors
	 */
	public final java.lang.Integer getDoors(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Doors.toString());
	}

	/**
	 * Set value of Doors
	 * @param doors
	 */
	public final void setDoors(java.lang.Integer doors)
	{
		setDoors(getContext(), doors);
	}

	/**
	 * Set value of Doors
	 * @param context
	 * @param doors
	 */
	public final void setDoors(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer doors)
	{
		getMendixObject().setValue(context, MemberNames.Doors.toString(), doors);
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of HasTurbo
	 */
	public final java.lang.Boolean getHasTurbo()
	{
		return getHasTurbo(getContext());
	}

	/**
	 * @param context
	 * @return value of HasTurbo
	 */
	public final java.lang.Boolean getHasTurbo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasTurbo.toString());
	}

	/**
	 * Set value of HasTurbo
	 * @param hasturbo
	 */
	public final void setHasTurbo(java.lang.Boolean hasturbo)
	{
		setHasTurbo(getContext(), hasturbo);
	}

	/**
	 * Set value of HasTurbo
	 * @param context
	 * @param hasturbo
	 */
	public final void setHasTurbo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasturbo)
	{
		getMendixObject().setValue(context, MemberNames.HasTurbo.toString(), hasturbo);
	}

	/**
	 * @return value of DateIntroduction
	 */
	public final java.util.Date getDateIntroduction()
	{
		return getDateIntroduction(getContext());
	}

	/**
	 * @param context
	 * @return value of DateIntroduction
	 */
	public final java.util.Date getDateIntroduction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateIntroduction.toString());
	}

	/**
	 * Set value of DateIntroduction
	 * @param dateintroduction
	 */
	public final void setDateIntroduction(java.util.Date dateintroduction)
	{
		setDateIntroduction(getContext(), dateintroduction);
	}

	/**
	 * Set value of DateIntroduction
	 * @param context
	 * @param dateintroduction
	 */
	public final void setDateIntroduction(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateintroduction)
	{
		getMendixObject().setValue(context, MemberNames.DateIntroduction.toString(), dateintroduction);
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final mxmustachetests.proxies.Color getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final mxmustachetests.proxies.Color getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Color.toString());
		if (obj == null)
			return null;

		return mxmustachetests.proxies.Color.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(mxmustachetests.proxies.Color color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, mxmustachetests.proxies.Color color)
	{
		if (color != null)
			getMendixObject().setValue(context, MemberNames.Color.toString(), color.toString());
		else
			getMendixObject().setValue(context, MemberNames.Color.toString(), null);
	}

	/**
	 * @return value of Car_CarList
	 */
	public final mxmustachetests.proxies.CarList getCar_CarList() throws com.mendix.core.CoreException
	{
		return getCar_CarList(getContext());
	}

	/**
	 * @param context
	 * @return value of Car_CarList
	 */
	public final mxmustachetests.proxies.CarList getCar_CarList(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmustachetests.proxies.CarList result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Car_CarList.toString());
		if (identifier != null)
			result = mxmustachetests.proxies.CarList.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Car_CarList
	 * @param car_carlist
	 */
	public final void setCar_CarList(mxmustachetests.proxies.CarList car_carlist)
	{
		setCar_CarList(getContext(), car_carlist);
	}

	/**
	 * Set value of Car_CarList
	 * @param context
	 * @param car_carlist
	 */
	public final void setCar_CarList(com.mendix.systemwideinterfaces.core.IContext context, mxmustachetests.proxies.CarList car_carlist)
	{
		if (car_carlist == null)
			getMendixObject().setValue(context, MemberNames.Car_CarList.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Car_CarList.toString(), car_carlist.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return carMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxmustachetests.proxies.Car that = (mxmustachetests.proxies.Car) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxMustacheTests.Car";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
