// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendixsso.proxies;

public class MendixSSOUser extends system.proxies.User
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MendixSSO.MendixSSOUser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		EmailAddress("EmailAddress"),
		AvatarURL("AvatarURL"),
		AvatarThumbURL("AvatarThumbURL"),
		HasSSOEnabled("HasSSOEnabled"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MendixSSOUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MendixSSO.MendixSSOUser"));
	}

	protected MendixSSOUser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixSSOUserMendixObject)
	{
		super(context, mendixSSOUserMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MendixSSO.MendixSSOUser", mendixSSOUserMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MendixSSO.MendixSSOUser");
	}

	/**
	 * @deprecated Use 'MendixSSOUser.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mendixsso.proxies.MendixSSOUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mendixsso.proxies.MendixSSOUser.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mendixsso.proxies.MendixSSOUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mendixsso.proxies.MendixSSOUser(context, mendixObject);
	}

	public static mendixsso.proxies.MendixSSOUser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mendixsso.proxies.MendixSSOUser.initialize(context, mendixObject);
	}

	public static java.util.List<mendixsso.proxies.MendixSSOUser> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mendixsso.proxies.MendixSSOUser> result = new java.util.ArrayList<mendixsso.proxies.MendixSSOUser>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MendixSSO.MendixSSOUser" + xpathConstraint))
			result.add(mendixsso.proxies.MendixSSOUser.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of AvatarURL
	 */
	public final java.lang.String getAvatarURL()
	{
		return getAvatarURL(getContext());
	}

	/**
	 * @param context
	 * @return value of AvatarURL
	 */
	public final java.lang.String getAvatarURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AvatarURL.toString());
	}

	/**
	 * Set value of AvatarURL
	 * @param avatarurl
	 */
	public final void setAvatarURL(java.lang.String avatarurl)
	{
		setAvatarURL(getContext(), avatarurl);
	}

	/**
	 * Set value of AvatarURL
	 * @param context
	 * @param avatarurl
	 */
	public final void setAvatarURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String avatarurl)
	{
		getMendixObject().setValue(context, MemberNames.AvatarURL.toString(), avatarurl);
	}

	/**
	 * @return value of AvatarThumbURL
	 */
	public final java.lang.String getAvatarThumbURL()
	{
		return getAvatarThumbURL(getContext());
	}

	/**
	 * @param context
	 * @return value of AvatarThumbURL
	 */
	public final java.lang.String getAvatarThumbURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AvatarThumbURL.toString());
	}

	/**
	 * Set value of AvatarThumbURL
	 * @param avatarthumburl
	 */
	public final void setAvatarThumbURL(java.lang.String avatarthumburl)
	{
		setAvatarThumbURL(getContext(), avatarthumburl);
	}

	/**
	 * Set value of AvatarThumbURL
	 * @param context
	 * @param avatarthumburl
	 */
	public final void setAvatarThumbURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String avatarthumburl)
	{
		getMendixObject().setValue(context, MemberNames.AvatarThumbURL.toString(), avatarthumburl);
	}

	/**
	 * @return value of HasSSOEnabled
	 */
	public final java.lang.Boolean getHasSSOEnabled()
	{
		return getHasSSOEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of HasSSOEnabled
	 */
	public final java.lang.Boolean getHasSSOEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasSSOEnabled.toString());
	}

	/**
	 * Set value of HasSSOEnabled
	 * @param hasssoenabled
	 */
	public final void setHasSSOEnabled(java.lang.Boolean hasssoenabled)
	{
		setHasSSOEnabled(getContext(), hasssoenabled);
	}

	/**
	 * Set value of HasSSOEnabled
	 * @param context
	 * @param hasssoenabled
	 */
	public final void setHasSSOEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasssoenabled)
	{
		getMendixObject().setValue(context, MemberNames.HasSSOEnabled.toString(), hasssoenabled);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mendixsso.proxies.MendixSSOUser that = (mendixsso.proxies.MendixSSOUser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MendixSSO.MendixSSOUser";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
