// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package inviteapi.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the InviteAPI module

	public static void sendInvite(IContext context, String _environmentUUID, String _environmentPassword, String _roleUUID, String _inviteeEmailAddress, String _inviterEmailAddress)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EnvironmentUUID", _environmentUUID);
			params.put("EnvironmentPassword", _environmentPassword);
			params.put("RoleUUID", _roleUUID);
			params.put("InviteeEmailAddress", _inviteeEmailAddress);
			params.put("InviterEmailAddress", _inviterEmailAddress);
			Core.execute(context, "InviteAPI.SendInvite", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}