// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mendixsso.actions;

import mendixsso.implementation.oidp.IdentityProviderMetaDataCache;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetTokenEndpointURI extends CustomJavaAction<java.lang.String>
{
	public GetTokenEndpointURI(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        return IdentityProviderMetaDataCache.getInstance().getIdentityProviderMetaData().getProviderMetadata().getTokenEndpointURI().toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetTokenEndpointURI";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
