// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxmustache.actions;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxmustache.template.TemplateEngineJMustache;
import java.util.HashMap;

public class FillTemplateFromJson extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Template;
	private java.lang.String JsonData;
	private java.lang.Boolean RunMarkdown;
	private java.lang.String DefaultValue;

	public FillTemplateFromJson(IContext context, java.lang.String Template, java.lang.String JsonData, java.lang.Boolean RunMarkdown, java.lang.String DefaultValue)
	{
		super(context);
		this.Template = Template;
		this.JsonData = JsonData;
		this.RunMarkdown = RunMarkdown;
		this.DefaultValue = DefaultValue;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        ILogNode logger = Core.getLogger(FillTemplate.class.getName());
        logger.info("executeAction: " + this.JsonData + ", " + this.Template);
        try {
            TemplateEngineJMustache te = new TemplateEngineJMustache();
            HashMap<String, Object> jsonData =
                    new ObjectMapper().readValue(JsonData, HashMap.class);
            logger.info("data: " + jsonData);
            String result = te.execute(this.Template, jsonData, this.RunMarkdown, this.DefaultValue);
            return result;
        } catch (Exception e) {
            logger.error(e);
            throw e;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FillTemplateFromJson";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
